"""SIF Sentence Embedder — Smooth Inverse Frequency for SOT v2.0.

Theoretical foundation:
    Arora et al. (2017) "A Simple but Tough-to-Beat Baseline for
    Sentence Embeddings" proves that under a generative model where
    sentences are generated by a random walk on a discourse vector,
    the optimal sentence embedding is:

        v_s = (1/|s|) Σ_{w∈s}  a / (a + p(w)) · v_w

    where p(w) is the unigram probability of word w, v_w is its word
    embedding, and a is a hyper-parameter (typically 1e-3 to 1e-4).

    After computing v_s, removing the first principal component from
    the corpus of sentence embeddings corrects for the common discourse
    direction and dramatically improves performance on semantic textual
    similarity tasks.

    This method is:
      - Unsupervised (no sentence-pair labels)
      - Theoretically grounded in a random-walk discourse model
      - Competitive with early SBERT variants on STS benchmarks
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional, Callable

import numpy as np

logger = logging.getLogger(__name__)


class SIFEmbedder:
    """Smooth Inverse Frequency sentence embedder.

    Trains word embeddings via PMI-based matrix factorisation, then
    composes sentence embeddings via SIF weighting + PCA removal.
    """

    def __init__(
        self,
        latent_dim: int = 384,
        window_size: int = 5,
        min_count: int = 2,
        a: float = 1e-3,
        remove_pc: bool = True,
        use_char_fallback: bool = True,
        char_ngram_range: tuple = (3, 4),
    ):
        self.latent_dim = latent_dim
        self.window_size = window_size
        self.min_count = min_count
        self.a = a
        self.remove_pc = remove_pc
        self.use_char_fallback = use_char_fallback
        self.char_ngram_range = char_ngram_range

        self.word_embeddings: Dict[int, np.ndarray] = {}
        self.word_probs: Dict[int, float] = {}
        self._pc: Optional[np.ndarray] = None  # First principal component
        self._aligner = None  # Optional ProcrustesAligner
        self._pmi_matrix: Optional[Any] = None  # Valid-token PMI (dense np.ndarray or scipy.sparse matrix)
        self._pmi_idx_map: Optional[Dict[int, int]] = None  # token_id -> pmi row
        self._pmi_valid_idx: Optional[List[int]] = None  # List of valid token IDs
        self.char_ngram_embeddings: Dict[str, np.ndarray] = {}  # "#ea" -> vector
        self._char_ngram_probs: Dict[str, float] = {}
        self._id2word: Optional[Dict[int, str]] = None

    @staticmethod
    def _randomized_svd(M: np.ndarray, n_components: int, n_oversamples: int = 10, n_iter: int = 2):
        """Randomized SVD via Halko et al. 2011 — O(n×d²) instead of O(n³).

        Suitable for large dense matrices where full SVD is prohibitive.
        """
        m, n = M.shape
        p = min(n, n_components + n_oversamples)
        rng = np.random.default_rng(42)
        Omega = rng.standard_normal(n, dtype=np.float32)
        if p > 1:
            Omega = np.column_stack([Omega] + [rng.standard_normal(n, dtype=np.float32) for _ in range(p - 1)])
        Y = M @ Omega
        for _ in range(n_iter):
            Y = M @ (M.T @ Y)
        Q, _ = np.linalg.qr(Y)
        B = Q.T @ M
        Uhat, S, Vt = np.linalg.svd(B, full_matrices=False)
        U = Q @ Uhat
        return U[:, :n_components], S[:n_components], Vt[:n_components, :]

    # ------------------------------------------------------------------ #
    # Training
    # ------------------------------------------------------------------ #

    def fit(
        self,
        tokenized_docs: List[List[int]],
        vocab_size: int,
        id2word: Optional[Dict[int, str]] = None,
    ) -> "SIFEmbedder":
        """Fit word embeddings and sentence PCA on tokenized documents.

        Args:
            tokenized_docs: List of documents, each a list of token IDs.
            vocab_size: Total number of distinct token IDs.
        """
        logger.info(
            "SIFEmbedder: fitting on %d docs, vocab=%d, dim=%d",
            len(tokenized_docs),
            vocab_size,
            self.latent_dim,
        )

        # 1. Count unigrams and co-occurrences (sparse to avoid OOM)
        unigram_counts = np.zeros(vocab_size, dtype=np.float64)
        from collections import defaultdict
        cooc_sparse = defaultdict(lambda: defaultdict(float))
        total_tokens = 0

        for doc in tokenized_docs:
            if not doc:
                continue
            for t in doc:
                if 0 <= t < vocab_size:
                    unigram_counts[t] += 1.0
                    total_tokens += 1
            w = self.window_size
            for i in range(len(doc)):
                for j in range(i + 1, min(i + w + 1, len(doc))):
                    a, b = doc[i], doc[j]
                    if 0 <= a < vocab_size and 0 <= b < vocab_size:
                        cooc_sparse[a][b] += 1.0
                        cooc_sparse[b][a] += 1.0

        if total_tokens == 0:
            raise ValueError("No tokens found in corpus")

        # Word probabilities
        self.word_probs = {
            t: float(unigram_counts[t]) / total_tokens
            for t in range(vocab_size)
            if unigram_counts[t] > 0
        }

        valid_mask = unigram_counts >= self.min_count
        n_valid = int(valid_mask.sum())
        logger.info(
            "SIFEmbedder: %d / %d tokens pass min_count=%d",
            n_valid,
            vocab_size,
            self.min_count,
        )

        if n_valid == 0:
            logger.warning("No valid tokens, using random embeddings")
            rng = np.random.default_rng(42)
            for t in range(vocab_size):
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb
            return self

        # 2. PMI matrix for valid tokens
        valid_idx = np.where(valid_mask)[0]
        idx_map = {int(v): i for i, v in enumerate(valid_idx)}
        import math

        SPARSE_PMI_THRESHOLD = 5000
        k = min(self.latent_dim, n_valid)

        if n_valid > SPARSE_PMI_THRESHOLD:
            # Sparse PMI path for large vocabularies — avoids O(n²) dense matrix
            logger.info("SIFEmbedder: building sparse PMI (n_valid=%d)", n_valid)
            from scipy.sparse import coo_matrix

            rows, cols, data = [], [], []
            for a, neighbors in cooc_sparse.items():
                if a not in idx_map:
                    continue
                ai = idx_map[a]
                for b, count in neighbors.items():
                    if b in idx_map:
                        rows.append(ai)
                        cols.append(idx_map[b])
                        data.append(count)

            cooc_coo = coo_matrix((data, (rows, cols)), shape=(n_valid, n_valid))
            N = float(cooc_coo.sum()) + 1e-8
            log_N = math.log(N)

            row_sums = np.array(cooc_coo.sum(axis=1)).flatten() + 1e-8
            col_sums = np.array(cooc_coo.sum(axis=0)).flatten() + 1e-8
            log_row = np.log(row_sums)
            log_col = np.log(col_sums)

            pmi_data, pmi_rows, pmi_cols = [], [], []
            for i, j, c in zip(cooc_coo.row, cooc_coo.col, cooc_coo.data):
                pmi_val = math.log(c + 1e-8) + log_N - log_row[i] - log_col[j]
                if pmi_val > 0:
                    pmi_data.append(pmi_val)
                    pmi_rows.append(i)
                    pmi_cols.append(j)

            from scipy.sparse import coo_matrix as _coo
            pmi = _coo((pmi_data, (pmi_rows, pmi_cols)), shape=(n_valid, n_valid)).tocsr()
            self._pmi_matrix = pmi
            self._pmi_idx_map = idx_map
            self._pmi_valid_idx = list(valid_idx)

            # Truncated SVD on sparse PMI via sklearn
            from sklearn.decomposition import TruncatedSVD
            svd = TruncatedSVD(n_components=k, algorithm="randomized", random_state=42)
            raw_emb = svd.fit_transform(pmi).astype(np.float32)
            norms = np.linalg.norm(raw_emb, axis=1, keepdims=True) + 1e-8
            raw_emb /= norms
        else:
            # Dense PMI path for small vocabularies — faster for small matrices
            u_counts = unigram_counts[valid_idx] + 1e-8
            c_counts = np.zeros((n_valid, n_valid), dtype=np.float64)
            for a, neighbors in cooc_sparse.items():
                if a not in idx_map:
                    continue
                ai = idx_map[a]
                for b, count in neighbors.items():
                    if b in idx_map:
                        c_counts[ai, idx_map[b]] = count
            N = float(c_counts.sum()) + 1e-8

            log_cij = np.log(c_counts + 1e-8)
            log_ci = np.log(u_counts)
            log_cj = np.log(u_counts)
            pmi = log_cij + math.log(N) - log_ci[:, None] - log_cj[None, :]
            pmi = np.maximum(pmi, 0.0).astype(np.float32)

            # Save PMI matrix for query expansion
            self._pmi_matrix = pmi
            self._pmi_idx_map = idx_map
            self._pmi_valid_idx = list(valid_idx)

            logger.info("SIFEmbedder: computing SVD on %dx%d PMI matrix...", n_valid, n_valid)
            if n_valid > 2000:
                U, S, _ = self._randomized_svd(pmi, n_components=k, n_oversamples=10, n_iter=2)
            else:
                U, S, _ = np.linalg.svd(pmi, full_matrices=False)
                U = U[:, :k]
                S = S[:k]
            Sk = np.sqrt(S)
            raw_emb = (U * Sk[None, :]).astype(np.float32)
            norms = np.linalg.norm(raw_emb, axis=1, keepdims=True) + 1e-8
            raw_emb /= norms

        # Adaptive SIF parameter: set a to 10th percentile of word probs
        if self.word_probs:
            probs = np.array(list(self.word_probs.values()), dtype=np.float32)
            adaptive_a = float(np.percentile(probs, 10))
            if adaptive_a > 0:
                logger.info(
                    "SIFEmbedder: adaptive a=%.6f (old a=%.6f)",
                    adaptive_a,
                    self.a,
                )
                self.a = adaptive_a

        for orig_t, sub_i in idx_map.items():
            emb = raw_emb[sub_i]
            if k < self.latent_dim:
                pad = np.zeros(self.latent_dim - k, dtype=np.float32)
                emb = np.concatenate([emb, pad])
            self.word_embeddings[orig_t] = emb

        rng = np.random.default_rng(42)
        for t in range(vocab_size):
            if t not in self.word_embeddings:
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb

        # 4. Compute first principal component of sentence embeddings
        if self.remove_pc:
            sentence_embs = []
            for doc in tokenized_docs:
                emb = self._embed_sentence_raw(doc)
                if emb is not None:
                    sentence_embs.append(emb)
            if len(sentence_embs) >= 2:
                X = np.stack(sentence_embs)
                # First PC via power iteration (faster than full SVD)
                self._pc = self._power_iteration(X, max_iter=10)
                logger.info("SIFEmbedder: first principal component computed")

        # 5. Fit character n-gram embeddings for OOV fallback
        if id2word is not None:
            self._id2word = id2word
        if self.use_char_fallback and self._id2word is not None:
            self._fit_char_ngrams(tokenized_docs, self._id2word)

        logger.info("SIFEmbedder: fit complete")
        return self

    # ------------------------------------------------------------------ #
    # Character n-gram fallback (FastText-style OOV handling)
    # ------------------------------------------------------------------ #

    @staticmethod
    def _char_ngrams(word: str, n: int) -> List[str]:
        """Extract character n-grams with boundary markers."""
        padded = f"#{word}#"
        if len(padded) < n:
            return [padded] if padded else []
        return [padded[i:i + n] for i in range(len(padded) - n + 1)]

    def _fit_char_ngrams(
        self,
        tokenized_docs: List[List[int]],
        id2word: Dict[int, str],
    ) -> None:
        """Derive character n-gram embeddings from word embeddings.

        For each character n-gram, its embedding is the mean of word
        embeddings for all corpus words that contain it.  This requires
        no external data and works with any alphabet.
        """
        logger.info("SIFEmbedder: fitting char n-gram fallback...")

        # Collect word embeddings and char n-gram occurrences
        ngram_to_vectors: Dict[str, List[np.ndarray]] = {}
        ngram_counts: Dict[str, int] = {}

        for doc in tokenized_docs:
            for t in doc:
                if t not in self.word_embeddings:
                    continue
                word = id2word.get(t, "")
                if not word:
                    continue
                emb = self.word_embeddings[t]
                for n in range(self.char_ngram_range[0], self.char_ngram_range[1] + 1):
                    for cg in self._char_ngrams(word, n):
                        ngram_to_vectors.setdefault(cg, []).append(emb)
                        ngram_counts[cg] = ngram_counts.get(cg, 0) + 1

        if not ngram_to_vectors:
            logger.warning("SIFEmbedder: no char n-grams could be derived")
            return

        # Average and normalize
        for cg, vecs in ngram_to_vectors.items():
            avg = np.mean(vecs, axis=0)
            norm = np.linalg.norm(avg) + 1e-8
            self.char_ngram_embeddings[cg] = (avg / norm).astype(np.float32)

        # Compute pseudo-probabilities for SIF weighting
        total = sum(ngram_counts.values()) + 1e-8
        self._char_ngram_probs = {cg: c / total for cg, c in ngram_counts.items()}

        logger.info(
            "SIFEmbedder: %d char n-grams derived from %d words",
            len(self.char_ngram_embeddings),
            sum(1 for t in id2word if t in self.word_embeddings),
        )

    def _get_char_fallback_embedding(self, word: str) -> Optional[np.ndarray]:
        """Compose word embedding from character n-grams."""
        if not self.char_ngram_embeddings or not word:
            return None
        vectors = []
        weights = []
        for n in range(self.char_ngram_range[0], self.char_ngram_range[1] + 1):
            for cg in self._char_ngrams(word, n):
                if cg in self.char_ngram_embeddings:
                    vectors.append(self.char_ngram_embeddings[cg])
                    weights.append(self._char_ngram_probs.get(cg, 1e-3))
        if not vectors:
            return None
        # Weighted average (rare char n-grams get higher weight)
        weights = np.array(weights, dtype=np.float32)
        weights = self.a / (self.a + weights)
        vecs = np.stack(vectors, axis=0) * weights[:, None]
        emb = np.sum(vecs, axis=0) / (weights.sum() + 1e-8)
        norm = np.linalg.norm(emb) + 1e-8
        return (emb / norm).astype(np.float32)

    def estimate_optimal_a(self, tokenized_docs: List[List[int]]) -> float:
        """Estimate data-adaptive SIF smoothing parameter a.

        Theory: Arora et al. fix a=1e-3, but optimal a depends on corpus
        statistics.  We set a to the 10th percentile of empirical word
        probabilities — this ensures common words are down-weighted without
        over-penalising domain-specific terms.
        """
        counts: Dict[int, int] = {}
        total = 0
        for doc in tokenized_docs:
            for t in doc:
                counts[t] = counts.get(t, 0) + 1
                total += 1
        if total == 0:
            return 1e-3
        probs = np.array([c / total for c in counts.values()], dtype=np.float32)
        return float(np.percentile(probs, 10))

    def expand_query(
        self,
        token_ids: List[int],
        n_terms: int = 3,
        min_pmi: float = 0.5,
    ) -> List[Tuple[int, float]]:
        """Expand query with PMI-based synonym terms.

        For each query token, find top-n co-occurring tokens by PMI.
        Returns list of (token_id, aggregate_pmi_score) sorted by score.

        Reference: Church & Hanks (1990) "Word Association Norms, Mutual
        Information, and Lexicography."
        """
        if self._pmi_matrix is None or self._pmi_idx_map is None:
            return []
        scores: Dict[int, float] = {}
        # Support both dense (np.ndarray) and sparse (scipy.sparse) PMI matrices
        is_sparse = hasattr(self._pmi_matrix, "getrow")
        for t in token_ids:
            if t not in self._pmi_idx_map:
                continue
            row = self._pmi_idx_map[t]
            if is_sparse:
                pmi_row = self._pmi_matrix.getrow(row)
                candidates = []
                for sub_j, pmi_val in zip(pmi_row.indices, pmi_row.data):
                    if pmi_val >= min_pmi:
                        orig_t = self._pmi_valid_idx[sub_j]
                        if orig_t != t:
                            candidates.append((orig_t, float(pmi_val)))
            else:
                pmi_row = self._pmi_matrix[row]
                candidates = []
                for sub_j, pmi_val in enumerate(pmi_row):
                    if pmi_val >= min_pmi:
                        orig_t = self._pmi_valid_idx[sub_j]
                        if orig_t != t:
                            candidates.append((orig_t, float(pmi_val)))
            candidates.sort(key=lambda x: x[1], reverse=True)
            for orig_t, pmi_val in candidates[:n_terms]:
                scores[orig_t] = scores.get(orig_t, 0.0) + pmi_val
        sorted_terms = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        return sorted_terms

    def _embed_sentence_raw(self, token_ids: List[int]) -> Optional[np.ndarray]:
        """SIF-weighted average without PC removal.

        Uses character n-gram fallback for OOV tokens when enabled.
        """
        if not token_ids:
            return None
        vecs = []
        weights = []
        for t in token_ids:
            if t in self.word_embeddings:
                p = self.word_probs.get(t, 1e-8)
                weight = self.a / (self.a + p)
                vecs.append(self.word_embeddings[t] * weight)
                weights.append(weight)
            elif self.use_char_fallback and self._id2word is not None:
                word = self._id2word.get(t, "")
                if word:
                    fallback = self._get_char_fallback_embedding(word)
                    if fallback is not None:
                        # Use a flat weight for fallback tokens (they don't have
                        # corpus frequency, so we assume moderate rarity)
                        weight = 0.5
                        vecs.append(fallback * weight)
                        weights.append(weight)
        if not vecs:
            return None
        emb = np.sum(vecs, axis=0) / (sum(weights) + 1e-8)
        return emb.astype(np.float32)

    def embed(self, token_ids: List[int]) -> np.ndarray:
        """Embed a sentence (list of token IDs) via SIF."""
        emb = self._embed_sentence_raw(token_ids)
        if emb is None:
            return np.zeros(self.latent_dim, dtype=np.float32)
        if self._pc is not None and self.remove_pc:
            # Remove projection onto first PC
            emb = emb - emb.dot(self._pc) * self._pc
        # Apply learnable projection if available
        if hasattr(self, '_projection') and self._projection is not None:
            emb = self._projection(emb)
        # Apply Procrustes alignment if available
        if self._aligner is not None:
            emb = self._aligner.transform(emb)
        norm = np.linalg.norm(emb) + 1e-8
        return (emb / norm).astype(np.float32)

    def align_to_teacher(
        self,
        sif_embs: np.ndarray,
        teacher_embs: np.ndarray,
        center: bool = True,
    ) -> "SIFEmbedder":
        """Align SIF embeddings to a teacher model via orthogonal Procrustes.

        This is lightweight knowledge distillation: after training SIF on
        unsupervised corpus data, we fit a single orthogonal matrix R that
        minimises ||SIF(corpus)·R − Teacher(corpus)||_F.  At inference time
        only the matrix multiplication is required (no PyTorch).

        Args:
            sif_embs: SIF embeddings for alignment corpus, shape (n, d).
            teacher_embs: Teacher embeddings for the same corpus, shape (n, d).
            center: Whether to mean-center both spaces before alignment.
        """
        from .procrustes import ProcrustesAligner

        self._aligner = ProcrustesAligner(d=sif_embs.shape[1])
        self._aligner.fit(sif_embs, teacher_embs, center=center)
        diag = self._aligner.diagnostics()
        logger.info(
            "SIFEmbedder: Procrustes alignment fitted — MSE=%.6f, mean_cosine=%.4f",
            diag["mse"],
            diag["mean_cosine"],
        )
        return self

    def add_projection_layer(self, hidden_dim: Optional[int] = None):
        """Add a small learnable MLP projection for domain adaptation.

        The projection is a single dense layer: ReLU(W·x + b).
        It is initialised as near-identity to preserve SIF quality.
        """
        rng = np.random.default_rng(42)
        h = hidden_dim or self.latent_dim
        self._proj_W = rng.standard_normal((self.latent_dim, h)).astype(np.float32) * 0.01
        self._proj_b = np.zeros(h, dtype=np.float32)
        self._proj_out = rng.standard_normal((h, self.latent_dim)).astype(np.float32) * 0.01
        self._proj_out_b = np.zeros(self.latent_dim, dtype=np.float32)
        # Near-identity shortcut
        self._proj_W[:min(self.latent_dim, h), :min(self.latent_dim, h)] += np.eye(
            min(self.latent_dim, h), dtype=np.float32
        )
        self._projection = lambda x: self._mlp_forward(x)

    def _mlp_forward(self, x: np.ndarray) -> np.ndarray:
        h = np.maximum(x @ self._proj_W + self._proj_b, 0)  # ReLU
        return h @ self._proj_out + self._proj_out_b

    def _mlp_backward(self, x: np.ndarray, grad_out: np.ndarray, lr: float = 0.001):
        # Simplified backprop for single layer MLP
        h_pre = x @ self._proj_W + self._proj_b
        h = np.maximum(h_pre, 0)
        grad_h = grad_out @ self._proj_out.T
        grad_h[h_pre <= 0] = 0  # ReLU derivative
        self._proj_W -= lr * np.outer(x, grad_h)
        self._proj_b -= lr * grad_h
        self._proj_out -= lr * np.outer(h, grad_out)
        self._proj_out_b -= lr * grad_out

    def contrastive_fine_tune_projection(
        self,
        tokenized_queries: List[List[int]],
        tokenized_positives: List[List[int]],
        n_epochs: int = 50,
        lr: float = 0.01,
        temperature: float = 0.05,
        n_negatives: int = 5,
    ) -> "SIFEmbedder":
        """Fine-tune only the projection MLP (preserves word embeddings).

        This avoids catastrophic forgetting because the pre-trained SIF
        word vectors are frozen; only the sentence-level projection is
        updated to match the retrieval task distribution.
        """
        if not hasattr(self, '_projection') or self._projection is None:
            self.add_projection_layer()

        N = len(tokenized_queries)
        if N == 0 or len(tokenized_positives) != N:
            raise ValueError("Queries and positives must have same length")

        logger.info(
            "SIFEmbedder: projection fine-tuning, N=%d, epochs=%d",
            N, n_epochs,
        )

        rng = np.random.default_rng(42)

        for epoch in range(n_epochs):
            total_loss = 0.0
            order = rng.permutation(N)
            for idx in order:
                q_emb = self.embed(tokenized_queries[idx])
                p_emb = self.embed(tokenized_positives[idx])

                neg_indices = rng.choice(
                    [i for i in range(N) if i != idx],
                    size=min(n_negatives, N - 1),
                    replace=False,
                )
                neg_embs = [self.embed(tokenized_positives[ni]) for ni in neg_indices]

                pos_sim = np.dot(q_emb, p_emb) / temperature
                neg_sims = np.array([np.dot(q_emb, ne) for ne in neg_embs]) / temperature
                logits = np.concatenate([[pos_sim], neg_sims])
                logits_max = logits.max()
                exp_logits = np.exp(logits - logits_max)
                loss = -np.log(exp_logits[0] / exp_logits.sum() + 1e-8)
                total_loss += float(loss)

                probs = exp_logits / (exp_logits.sum() + 1e-8)
                # Gradient w.r.t. query embedding
                d_q = -(p_emb - sum(probs[i+1] * neg_embs[i] for i in range(len(neg_embs)))) / temperature
                # Backprop through projection only
                q_raw = self._embed_sentence_raw(tokenized_queries[idx])
                if q_raw is not None:
                    self._mlp_backward(q_raw, d_q, lr=lr)

            if epoch % 10 == 0:
                logger.info(
                    "SIFEmbedder: projection epoch %d, avg loss=%.4f",
                    epoch,
                    total_loss / max(N, 1),
                )

        logger.info("SIFEmbedder: projection fine-tuning complete")
        return self

    @staticmethod
    def _power_iteration(X: np.ndarray, max_iter: int = 10) -> np.ndarray:
        """Compute dominant eigenvector of X^T X via power iteration."""
        v = np.random.default_rng(42).standard_normal(X.shape[1]).astype(np.float32)
        v /= np.linalg.norm(v) + 1e-8
        for _ in range(max_iter):
            v = X.T @ (X @ v)
            v /= np.linalg.norm(v) + 1e-8
        return v.astype(np.float32)

    def contrastive_fine_tune(
        self,
        tokenized_queries: List[List[int]],
        tokenized_positives: List[List[int]],
        n_epochs: int = 30,
        lr: float = 0.01,
        temperature: float = 0.05,
        n_negatives: int = 10,
    ) -> "SIFEmbedder":
        """Fine-tune word embeddings via InfoNCE loss.

        Theoretical foundation:
            InfoNCE (Oord et al. 2018) maximises a lower bound on the
            mutual information I(q; c) between query q and context c:

                L = -E[ log( exp(sim(q,p)/τ) / Σ_n exp(sim(q,n)/τ) ) ]

            Under the representation learning framework, minimising this
            loss pushes the query embedding toward its positive context
            and away from sampled negatives, which tightens the bound on
            MI and therefore improves retrieval discriminability.

        Args:
            tokenized_queries: One list of token IDs per query.
            tokenized_positives: One list of token IDs per positive context.
            n_epochs: Number of contrastive epochs.
            lr: Learning rate for word embedding updates.
            temperature: Temperature τ for InfoNCE scaling.
            n_negatives: Number of in-batch negatives per query.
        """
        N = len(tokenized_queries)
        if N == 0 or len(tokenized_positives) != N:
            raise ValueError("Queries and positives must have same length")

        logger.info(
            "SIFEmbedder: contrastive fine-tuning, N=%d, epochs=%d, lr=%.4f",
            N, n_epochs, lr,
        )

        rng = np.random.default_rng(42)

        for epoch in range(n_epochs):
            total_loss = 0.0
            order = rng.permutation(N)
            for idx in order:
                q_tokens = [t for t in tokenized_queries[idx] if t in self.word_embeddings]
                p_tokens = [t for t in tokenized_positives[idx] if t in self.word_embeddings]
                if not q_tokens or not p_tokens:
                    continue

                q_emb = self._embed_sentence_raw(q_tokens)
                p_emb = self._embed_sentence_raw(p_tokens)
                if q_emb is None or p_emb is None:
                    continue

                # Sample negatives
                neg_indices = rng.choice(
                    [i for i in range(N) if i != idx],
                    size=min(n_negatives, N - 1),
                    replace=False,
                )
                neg_embs = []
                for ni in neg_indices:
                    n_tokens = [t for t in tokenized_positives[ni] if t in self.word_embeddings]
                    if n_tokens:
                        ne = self._embed_sentence_raw(n_tokens)
                        if ne is not None:
                            neg_embs.append(ne)
                if not neg_embs:
                    continue

                # InfoNCE loss
                pos_sim = np.dot(q_emb, p_emb) / temperature
                neg_sims = np.array([np.dot(q_emb, ne) for ne in neg_embs]) / temperature
                logits = np.concatenate([[pos_sim], neg_sims])
                # Numerical stability
                logits_max = logits.max()
                exp_logits = np.exp(logits - logits_max)
                loss = -np.log(exp_logits[0] / exp_logits.sum() + 1e-8)
                total_loss += float(loss)

                # Gradient w.r.t. query and positive embeddings
                # Correct InfoNCE gradient: dL/dq = -( (1-p₀)*p - Σ pᵢ*nᵢ ) / τ
                probs = exp_logits / (exp_logits.sum() + 1e-8)
                pos_prob = float(probs[0])
                neg_weighted = sum(probs[i+1] * neg_embs[i] for i in range(len(neg_embs)))
                d_q = -( (1.0 - pos_prob) * p_emb - neg_weighted ) / temperature
                d_p = -( (1.0 - pos_prob) * q_emb ) / temperature

                # Backpropagate to word embeddings via average gradient
                # (simplified: treat each word as contributing equally to sentence emb)
                for t in q_tokens:
                    w = self.a / (self.a + self.word_probs.get(t, 1e-8))
                    self.word_embeddings[t] += lr * d_q * w / len(q_tokens)
                for t in p_tokens:
                    w = self.a / (self.a + self.word_probs.get(t, 1e-8))
                    self.word_embeddings[t] += lr * d_p * w / len(p_tokens)

                # Renormalise updated embeddings
                for t in set(q_tokens + p_tokens):
                    vec = self.word_embeddings[t]
                    norm = np.linalg.norm(vec) + 1e-8
                    self.word_embeddings[t] = (vec / norm).astype(np.float32)

            if epoch % 5 == 0:
                logger.info(
                    "SIFEmbedder: contrastive epoch %d, avg loss=%.4f",
                    epoch,
                    total_loss / max(N, 1),
                )

        # Recompute first PC after fine-tuning
        if self.remove_pc:
            sentence_embs = []
            for q_tokens, p_tokens in zip(tokenized_queries, tokenized_positives):
                for tokens in (q_tokens, p_tokens):
                    emb = self._embed_sentence_raw(tokens)
                    if emb is not None:
                        sentence_embs.append(emb)
            if len(sentence_embs) >= 2:
                X = np.stack(sentence_embs)
                self._pc = self._power_iteration(X, max_iter=10)
                logger.info("SIFEmbedder: first PC recomputed after fine-tuning")

        logger.info("SIFEmbedder: contrastive fine-tuning complete")
        return self

    def contrastive_distill(
        self,
        sif_embs: np.ndarray,
        teacher_embs: np.ndarray,
        n_epochs: int = 20,
        lr: float = 0.01,
        n_negatives: int = 5,
        margin: float = 0.2,
    ) -> "SIFEmbedder":
        """Local-preserving alignment via contrastive distillation.

        Instead of global Procrustes (which destroys local structure), we
        train a linear projection W that preserves nearest-neighbor
        relationships from the teacher space.

        Args:
            sif_embs: SIF sentence embeddings (n, latent_dim).
            teacher_embs: Teacher embeddings (n, latent_dim).
            n_epochs: Training epochs.
            lr: Learning rate.
            n_negatives: Number of negatives per positive.
            margin: Triplet loss margin.
        """
        n, d = sif_embs.shape
        if n < 10:
            logger.warning("contrastive_distill: too few samples (%d), skipping", n)
            return self

        # Normalize both spaces
        sif_norm = sif_embs / (np.linalg.norm(sif_embs, axis=1, keepdims=True) + 1e-8)
        teacher_norm = teacher_embs / (np.linalg.norm(teacher_embs, axis=1, keepdims=True) + 1e-8)

        # Build teacher nearest-neighbor graph
        teacher_sims = teacher_norm @ teacher_norm.T
        np.fill_diagonal(teacher_sims, -1.0)
        teacher_nn = np.argmax(teacher_sims, axis=1)

        # Initialize W as identity
        W = np.eye(d, dtype=np.float32)

        logger.info("SIFEmbedder: contrastive distillation on %d samples...", n)
        for epoch in range(n_epochs):
            total_loss = 0.0
            indices = np.random.permutation(n)
            for i in indices:
                x_i = sif_norm[i]
                pos_idx = teacher_nn[i]
                x_pos = sif_norm[pos_idx]

                # Negative sampling: hard negatives in teacher space
                neg_scores = teacher_sims[i]
                neg_candidates = np.argsort(neg_scores)[-n_negatives:]
                for neg_idx in neg_candidates:
                    if neg_idx == i:
                        continue
                    x_neg = sif_norm[neg_idx]

                    # Projected similarities
                    sim_pos = float(x_i @ W @ x_pos)
                    sim_neg = float(x_i @ W @ x_neg)

                    loss = max(0.0, margin + sim_neg - sim_pos)
                    if loss > 0:
                        # Gradient: dL/dW = x_i^T (x_neg - x_pos)
                        grad = np.outer(x_i, x_neg - x_pos)
                        W -= lr * grad
                        total_loss += loss

            avg_loss = total_loss / max(n, 1)
            if epoch % 5 == 0:
                logger.info("SIFEmbedder: distill epoch %d, avg loss=%.4f", epoch, avg_loss)

        # Orthonormalize W (prevent collapse)
        u, s, vt = np.linalg.svd(W)
        W = (u @ vt).astype(np.float32)

        # Apply W to all word embeddings (linear projection preserves composition)
        for tid in self.word_embeddings:
            self.word_embeddings[tid] = (W @ self.word_embeddings[tid]).astype(np.float32)
            self.word_embeddings[tid] /= np.linalg.norm(self.word_embeddings[tid]) + 1e-8

        # Also apply to char ngram embeddings
        for ng in self.char_ngram_embeddings:
            self.char_ngram_embeddings[ng] = (W @ self.char_ngram_embeddings[ng]).astype(np.float32)
            self.char_ngram_embeddings[ng] /= np.linalg.norm(self.char_ngram_embeddings[ng]) + 1e-8

        logger.info("SIFEmbedder: contrastive distillation complete")
        return self

    def get_state(self) -> dict:
        state = {
            "latent_dim": self.latent_dim,
            "a": self.a,
            "remove_pc": self.remove_pc,
            "use_char_fallback": self.use_char_fallback,
            "word_embeddings": {k: v.tolist() for k, v in self.word_embeddings.items()},
            "word_probs": self.word_probs,
            "pc": self._pc.tolist() if self._pc is not None else None,
            "char_ngram_embeddings": {k: v.tolist() for k, v in self.char_ngram_embeddings.items()},
        }
        if self._aligner is not None:
            state["aligner_diagnostics"] = self._aligner.diagnostics()
        return state

    def online_update(
        self,
        new_tokenized_docs: List[List[int]],
        lr: float = 0.001,
    ) -> "SIFEmbedder":
        """Incrementally update word embeddings with new documents.

        Theoretical foundation:
            Instead of recomputing the full PMI matrix and SVD, we treat
            each new co-occurrence observation as a stochastic gradient
            on the PMI objective:

                L_{ij} = (e_i^T e_j - PMI_{ij})^2

            For a new co-occurrence (i,j), the gradient w.r.t. e_i is:

                ∇_{e_i} = 2 (e_i^T e_j - PMI_{ij}) e_j

            This is online matrix factorisation (Mairal et al. 2010)
            applied to the PMI graph.

        Args:
            new_tokenized_docs: List of new documents (token ID lists).
            lr: Learning rate for stochastic gradient updates.
        """
        if not self.word_embeddings:
            raise RuntimeError("online_update called before fit()")

        logger.info("SIFEmbedder: online update with %d new docs", len(new_tokenized_docs))

        # Update unigram counts and co-occurrences
        total_new_tokens = 0
        for doc in new_tokenized_docs:
            for t in doc:
                if t in self.word_embeddings:
                    # Update unigram count (approximate: use running average)
                    self.word_probs[t] = 0.9 * self.word_probs.get(t, 0.0) + 0.1
                    total_new_tokens += 1
            w = self.window_size
            for i in range(len(doc)):
                for j in range(i + 1, min(i + w + 1, len(doc))):
                    a, b = doc[i], doc[j]
                    if a in self.word_embeddings and b in self.word_embeddings:
                        # Stochastic gradient update on PMI objective
                        e_a = self.word_embeddings[a]
                        e_b = self.word_embeddings[b]
                        # Approximate PMI as sign of co-occurrence
                        pmi_target = 1.0  # positive co-occurrence
                        pred = float(np.dot(e_a, e_b))
                        error = pred - pmi_target
                        # Gradient update
                        self.word_embeddings[a] -= lr * error * e_b
                        self.word_embeddings[b] -= lr * error * e_a
                        # Renormalise
                        self.word_embeddings[a] /= np.linalg.norm(self.word_embeddings[a]) + 1e-8
                        self.word_embeddings[b] /= np.linalg.norm(self.word_embeddings[b]) + 1e-8

        # Renormalise word_probs
        total_prob = sum(self.word_probs.values()) + 1e-8
        self.word_probs = {k: v / total_prob for k, v in self.word_probs.items()}

        logger.info("SIFEmbedder: online update complete, processed %d tokens", total_new_tokens)
        return self

    def load_state(self, state: dict) -> "SIFEmbedder":
        self.latent_dim = state["latent_dim"]
        self.a = state["a"]
        self.remove_pc = state["remove_pc"]
        self.use_char_fallback = state.get("use_char_fallback", True)
        self.word_embeddings = {
            int(k): np.array(v, dtype=np.float32)
            for k, v in state["word_embeddings"].items()
        }
        self.word_probs = {int(k): v for k, v in state["word_probs"].items()}
        pc = state.get("pc")
        self._pc = np.array(pc, dtype=np.float32) if pc is not None else None
        self.char_ngram_embeddings = {
            k: np.array(v, dtype=np.float32)
            for k, v in state.get("char_ngram_embeddings", {}).items()
        }
        # Note: aligner must be loaded separately via ProcrustesAligner.load()
        return self

    def save_npz(self, path: str):
        """Save to compact NPZ binary format (~10x smaller than JSON)."""
        # Word embeddings: stacked array + token_ids
        if self.word_embeddings:
            token_ids = np.array(sorted(self.word_embeddings.keys()), dtype=np.int32)
            word_emb_matrix = np.stack([self.word_embeddings[t] for t in token_ids])
        else:
            token_ids = np.array([], dtype=np.int32)
            word_emb_matrix = np.array([])

        # Char ngram embeddings
        if self.char_ngram_embeddings:
            ngram_keys = sorted(self.char_ngram_embeddings.keys())
            ngram_matrix = np.stack([self.char_ngram_embeddings[k] for k in ngram_keys])
        else:
            ngram_keys = []
            ngram_matrix = np.array([])

        # Word probs
        prob_ids = np.array(sorted(self.word_probs.keys()), dtype=np.int32)
        prob_values = np.array([self.word_probs[t] for t in prob_ids], dtype=np.float32)

        np.savez_compressed(
            path,
            latent_dim=self.latent_dim,
            a=self.a,
            remove_pc=self.remove_pc,
            use_char_fallback=self.use_char_fallback,
            token_ids=token_ids,
            word_emb_matrix=word_emb_matrix,
            prob_ids=prob_ids,
            prob_values=prob_values,
            pc=self._pc if self._pc is not None else np.array([]),
            ngram_keys=ngram_keys,
            ngram_matrix=ngram_matrix,
        )
        logger.info("SIFEmbedder: saved NPZ to %s", path)

    @classmethod
    def load_npz(cls, path: str) -> "SIFEmbedder":
        """Load from compact NPZ binary format."""
        data = np.load(path, allow_pickle=True)
        inst = cls(
            latent_dim=int(data["latent_dim"]),
            a=float(data["a"]),
            remove_pc=bool(data["remove_pc"]),
            use_char_fallback=bool(data.get("use_char_fallback", True)),
        )
        token_ids = data["token_ids"]
        word_emb_matrix = data["word_emb_matrix"]
        if len(token_ids) > 0 and len(word_emb_matrix) > 0:
            inst.word_embeddings = {
                int(tid): word_emb_matrix[i]
                for i, tid in enumerate(token_ids)
            }
        prob_ids = data["prob_ids"]
        prob_values = data["prob_values"]
        if len(prob_ids) > 0:
            inst.word_probs = {int(tid): float(v) for tid, v in zip(prob_ids, prob_values)}
        pc = data["pc"]
        if len(pc) > 0:
            inst._pc = pc.astype(np.float32)
        ngram_keys = data.get("ngram_keys", [])
        ngram_matrix = data.get("ngram_matrix", np.array([]))
        if len(ngram_keys) > 0 and len(ngram_matrix) > 0:
            inst.char_ngram_embeddings = {
                str(k): ngram_matrix[i]
                for i, k in enumerate(ngram_keys)
            }
        logger.info("SIFEmbedder: loaded NPZ from %s", path)
        return inst
