"""SIF Sentence Embedder — Smooth Inverse Frequency for SOT v2.0.

Theoretical foundation:
    Arora et al. (2017) "A Simple but Tough-to-Beat Baseline for
    Sentence Embeddings" proves that under a generative model where
    sentences are generated by a random walk on a discourse vector,
    the optimal sentence embedding is:

        v_s = (1/|s|) Σ_{w∈s}  a / (a + p(w)) · v_w

    where p(w) is the unigram probability of word w, v_w is its word
    embedding, and a is a hyper-parameter (typically 1e-3 to 1e-4).

    After computing v_s, removing the first principal component from
    the corpus of sentence embeddings corrects for the common discourse
    direction and dramatically improves performance on semantic textual
    similarity tasks.

    This method is:
      - Unsupervised (no sentence-pair labels)
      - Theoretically grounded in a random-walk discourse model
      - Competitive with early SBERT variants on STS benchmarks
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)


class SIFEmbedder:
    """Smooth Inverse Frequency sentence embedder.

    Trains word embeddings via PMI-based matrix factorisation, then
    composes sentence embeddings via SIF weighting + PCA removal.
    """

    def __init__(
        self,
        latent_dim: int = 384,
        window_size: int = 5,
        min_count: int = 2,
        a: float = 1e-3,
        remove_pc: bool = True,
    ):
        self.latent_dim = latent_dim
        self.window_size = window_size
        self.min_count = min_count
        self.a = a
        self.remove_pc = remove_pc

        self.word_embeddings: Dict[int, np.ndarray] = {}
        self.word_probs: Dict[int, float] = {}
        self._pc: Optional[np.ndarray] = None  # First principal component

    # ------------------------------------------------------------------ #
    # Training
    # ------------------------------------------------------------------ #

    def fit(
        self,
        tokenized_docs: List[List[int]],
        vocab_size: int,
    ) -> "SIFEmbedder":
        """Fit word embeddings and sentence PCA on tokenized documents.

        Args:
            tokenized_docs: List of documents, each a list of token IDs.
            vocab_size: Total number of distinct token IDs.
        """
        logger.info(
            "SIFEmbedder: fitting on %d docs, vocab=%d, dim=%d",
            len(tokenized_docs),
            vocab_size,
            self.latent_dim,
        )

        # 1. Count unigrams and co-occurrences
        unigram_counts = np.zeros(vocab_size, dtype=np.float64)
        cooc_counts = np.zeros((vocab_size, vocab_size), dtype=np.float64)
        total_tokens = 0

        for doc in tokenized_docs:
            if not doc:
                continue
            for t in doc:
                if 0 <= t < vocab_size:
                    unigram_counts[t] += 1.0
                    total_tokens += 1
            w = self.window_size
            for i in range(len(doc)):
                for j in range(i + 1, min(i + w + 1, len(doc))):
                    a, b = doc[i], doc[j]
                    if 0 <= a < vocab_size and 0 <= b < vocab_size:
                        cooc_counts[a, b] += 1.0
                        cooc_counts[b, a] += 1.0

        if total_tokens == 0:
            raise ValueError("No tokens found in corpus")

        # Word probabilities
        self.word_probs = {
            t: float(unigram_counts[t]) / total_tokens
            for t in range(vocab_size)
            if unigram_counts[t] > 0
        }

        valid_mask = unigram_counts >= self.min_count
        n_valid = int(valid_mask.sum())
        logger.info(
            "SIFEmbedder: %d / %d tokens pass min_count=%d",
            n_valid,
            vocab_size,
            self.min_count,
        )

        if n_valid == 0:
            logger.warning("No valid tokens, using random embeddings")
            rng = np.random.default_rng(42)
            for t in range(vocab_size):
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb
            return self

        # 2. PMI matrix for valid tokens
        valid_idx = np.where(valid_mask)[0]
        idx_map = {int(v): i for i, v in enumerate(valid_idx)}
        u_counts = unigram_counts[valid_idx] + 1e-8
        c_counts = cooc_counts[np.ix_(valid_idx, valid_idx)]
        N = float(c_counts.sum()) + 1e-8

        log_cij = np.log(c_counts + 1e-8)
        log_ci = np.log(u_counts)
        log_cj = np.log(u_counts)
        import math
        pmi = log_cij + math.log(N) - log_ci[:, None] - log_cj[None, :]
        pmi = np.maximum(pmi, 0.0).astype(np.float32)

        # 3. Truncated SVD
        logger.info("SIFEmbedder: computing SVD on %dx%d PMI matrix...", n_valid, n_valid)
        U, S, Vt = np.linalg.svd(pmi, full_matrices=False)
        k = min(self.latent_dim, n_valid)
        Uk = U[:, :k]
        Sk = np.sqrt(S[:k])
        raw_emb = (Uk * Sk[None, :]).astype(np.float32)
        norms = np.linalg.norm(raw_emb, axis=1, keepdims=True) + 1e-8
        raw_emb /= norms

        for orig_t, sub_i in idx_map.items():
            emb = raw_emb[sub_i]
            if k < self.latent_dim:
                pad = np.zeros(self.latent_dim - k, dtype=np.float32)
                emb = np.concatenate([emb, pad])
            self.word_embeddings[orig_t] = emb

        rng = np.random.default_rng(42)
        for t in range(vocab_size):
            if t not in self.word_embeddings:
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb

        # 4. Compute first principal component of sentence embeddings
        if self.remove_pc:
            sentence_embs = []
            for doc in tokenized_docs:
                emb = self._embed_sentence_raw(doc)
                if emb is not None:
                    sentence_embs.append(emb)
            if len(sentence_embs) >= 2:
                X = np.stack(sentence_embs)
                # First PC via power iteration (faster than full SVD)
                self._pc = self._power_iteration(X, max_iter=10)
                logger.info("SIFEmbedder: first principal component computed")

        logger.info("SIFEmbedder: fit complete")
        return self

    def _embed_sentence_raw(self, token_ids: List[int]) -> Optional[np.ndarray]:
        """SIF-weighted average without PC removal."""
        if not token_ids:
            return None
        vecs = []
        weights = []
        for t in token_ids:
            if t not in self.word_embeddings:
                continue
            p = self.word_probs.get(t, 1e-8)
            weight = self.a / (self.a + p)
            vecs.append(self.word_embeddings[t] * weight)
            weights.append(weight)
        if not vecs:
            return None
        emb = np.sum(vecs, axis=0) / (sum(weights) + 1e-8)
        return emb.astype(np.float32)

    def embed(self, token_ids: List[int]) -> np.ndarray:
        """Embed a sentence (list of token IDs) via SIF."""
        emb = self._embed_sentence_raw(token_ids)
        if emb is None:
            return np.zeros(self.latent_dim, dtype=np.float32)
        if self._pc is not None and self.remove_pc:
            # Remove projection onto first PC
            emb = emb - emb.dot(self._pc) * self._pc
        # Apply learnable projection if available
        if hasattr(self, '_projection') and self._projection is not None:
            emb = self._projection(emb)
        norm = np.linalg.norm(emb) + 1e-8
        return (emb / norm).astype(np.float32)

    def add_projection_layer(self, hidden_dim: Optional[int] = None):
        """Add a small learnable MLP projection for domain adaptation.

        The projection is a single dense layer: ReLU(W·x + b).
        It is initialised as near-identity to preserve SIF quality.
        """
        rng = np.random.default_rng(42)
        h = hidden_dim or self.latent_dim
        self._proj_W = rng.standard_normal((self.latent_dim, h)).astype(np.float32) * 0.01
        self._proj_b = np.zeros(h, dtype=np.float32)
        self._proj_out = rng.standard_normal((h, self.latent_dim)).astype(np.float32) * 0.01
        self._proj_out_b = np.zeros(self.latent_dim, dtype=np.float32)
        # Near-identity shortcut
        self._proj_W[:min(self.latent_dim, h), :min(self.latent_dim, h)] += np.eye(
            min(self.latent_dim, h), dtype=np.float32
        )
        self._projection = lambda x: self._mlp_forward(x)

    def _mlp_forward(self, x: np.ndarray) -> np.ndarray:
        h = np.maximum(x @ self._proj_W + self._proj_b, 0)  # ReLU
        return h @ self._proj_out + self._proj_out_b

    def _mlp_backward(self, x: np.ndarray, grad_out: np.ndarray, lr: float = 0.001):
        # Simplified backprop for single layer MLP
        h_pre = x @ self._proj_W + self._proj_b
        h = np.maximum(h_pre, 0)
        grad_h = grad_out @ self._proj_out.T
        grad_h[h_pre <= 0] = 0  # ReLU derivative
        self._proj_W -= lr * np.outer(x, grad_h)
        self._proj_b -= lr * grad_h
        self._proj_out -= lr * np.outer(h, grad_out)
        self._proj_out_b -= lr * grad_out

    def contrastive_fine_tune_projection(
        self,
        tokenized_queries: List[List[int]],
        tokenized_positives: List[List[int]],
        n_epochs: int = 50,
        lr: float = 0.01,
        temperature: float = 0.05,
        n_negatives: int = 5,
    ) -> "SIFEmbedder":
        """Fine-tune only the projection MLP (preserves word embeddings).

        This avoids catastrophic forgetting because the pre-trained SIF
        word vectors are frozen; only the sentence-level projection is
        updated to match the retrieval task distribution.
        """
        if not hasattr(self, '_projection') or self._projection is None:
            self.add_projection_layer()

        N = len(tokenized_queries)
        if N == 0 or len(tokenized_positives) != N:
            raise ValueError("Queries and positives must have same length")

        logger.info(
            "SIFEmbedder: projection fine-tuning, N=%d, epochs=%d",
            N, n_epochs,
        )

        rng = np.random.default_rng(42)

        for epoch in range(n_epochs):
            total_loss = 0.0
            order = rng.permutation(N)
            for idx in order:
                q_emb = self.embed(tokenized_queries[idx])
                p_emb = self.embed(tokenized_positives[idx])

                neg_indices = rng.choice(
                    [i for i in range(N) if i != idx],
                    size=min(n_negatives, N - 1),
                    replace=False,
                )
                neg_embs = [self.embed(tokenized_positives[ni]) for ni in neg_indices]

                pos_sim = np.dot(q_emb, p_emb) / temperature
                neg_sims = np.array([np.dot(q_emb, ne) for ne in neg_embs]) / temperature
                logits = np.concatenate([[pos_sim], neg_sims])
                logits_max = logits.max()
                exp_logits = np.exp(logits - logits_max)
                loss = -np.log(exp_logits[0] / exp_logits.sum() + 1e-8)
                total_loss += float(loss)

                probs = exp_logits / (exp_logits.sum() + 1e-8)
                # Gradient w.r.t. query embedding
                d_q = -(p_emb - sum(probs[i+1] * neg_embs[i] for i in range(len(neg_embs)))) / temperature
                # Backprop through projection only
                q_raw = self._embed_sentence_raw(tokenized_queries[idx])
                if q_raw is not None:
                    self._mlp_backward(q_raw, d_q, lr=lr)

            if epoch % 10 == 0:
                logger.info(
                    "SIFEmbedder: projection epoch %d, avg loss=%.4f",
                    epoch,
                    total_loss / max(N, 1),
                )

        logger.info("SIFEmbedder: projection fine-tuning complete")
        return self

    @staticmethod
    def _power_iteration(X: np.ndarray, max_iter: int = 10) -> np.ndarray:
        """Compute dominant eigenvector of X^T X via power iteration."""
        v = np.random.default_rng(42).standard_normal(X.shape[1]).astype(np.float32)
        v /= np.linalg.norm(v) + 1e-8
        for _ in range(max_iter):
            v = X.T @ (X @ v)
            v /= np.linalg.norm(v) + 1e-8
        return v.astype(np.float32)

    def contrastive_fine_tune(
        self,
        tokenized_queries: List[List[int]],
        tokenized_positives: List[List[int]],
        n_epochs: int = 30,
        lr: float = 0.01,
        temperature: float = 0.05,
        n_negatives: int = 10,
    ) -> "SIFEmbedder":
        """Fine-tune word embeddings via InfoNCE loss.

        Theoretical foundation:
            InfoNCE (Oord et al. 2018) maximises a lower bound on the
            mutual information I(q; c) between query q and context c:

                L = -E[ log( exp(sim(q,p)/τ) / Σ_n exp(sim(q,n)/τ) ) ]

            Under the representation learning framework, minimising this
            loss pushes the query embedding toward its positive context
            and away from sampled negatives, which tightens the bound on
            MI and therefore improves retrieval discriminability.

        Args:
            tokenized_queries: One list of token IDs per query.
            tokenized_positives: One list of token IDs per positive context.
            n_epochs: Number of contrastive epochs.
            lr: Learning rate for word embedding updates.
            temperature: Temperature τ for InfoNCE scaling.
            n_negatives: Number of in-batch negatives per query.
        """
        N = len(tokenized_queries)
        if N == 0 or len(tokenized_positives) != N:
            raise ValueError("Queries and positives must have same length")

        logger.info(
            "SIFEmbedder: contrastive fine-tuning, N=%d, epochs=%d, lr=%.4f",
            N, n_epochs, lr,
        )

        rng = np.random.default_rng(42)

        for epoch in range(n_epochs):
            total_loss = 0.0
            order = rng.permutation(N)
            for idx in order:
                q_tokens = [t for t in tokenized_queries[idx] if t in self.word_embeddings]
                p_tokens = [t for t in tokenized_positives[idx] if t in self.word_embeddings]
                if not q_tokens or not p_tokens:
                    continue

                q_emb = self._embed_sentence_raw(q_tokens)
                p_emb = self._embed_sentence_raw(p_tokens)
                if q_emb is None or p_emb is None:
                    continue

                # Sample negatives
                neg_indices = rng.choice(
                    [i for i in range(N) if i != idx],
                    size=min(n_negatives, N - 1),
                    replace=False,
                )
                neg_embs = []
                for ni in neg_indices:
                    n_tokens = [t for t in tokenized_positives[ni] if t in self.word_embeddings]
                    if n_tokens:
                        ne = self._embed_sentence_raw(n_tokens)
                        if ne is not None:
                            neg_embs.append(ne)
                if not neg_embs:
                    continue

                # InfoNCE loss
                pos_sim = np.dot(q_emb, p_emb) / temperature
                neg_sims = np.array([np.dot(q_emb, ne) for ne in neg_embs]) / temperature
                logits = np.concatenate([[pos_sim], neg_sims])
                # Numerical stability
                logits_max = logits.max()
                exp_logits = np.exp(logits - logits_max)
                loss = -np.log(exp_logits[0] / exp_logits.sum() + 1e-8)
                total_loss += float(loss)

                # Gradient w.r.t. query and positive embeddings
                probs = exp_logits / (exp_logits.sum() + 1e-8)
                d_q = -(p_emb - sum(probs[i+1] * neg_embs[i] for i in range(len(neg_embs)))) / temperature
                d_p = -q_emb / temperature

                # Backpropagate to word embeddings via average gradient
                # (simplified: treat each word as contributing equally to sentence emb)
                for t in q_tokens:
                    w = self.a / (self.a + self.word_probs.get(t, 1e-8))
                    self.word_embeddings[t] += lr * d_q * w / len(q_tokens)
                for t in p_tokens:
                    w = self.a / (self.a + self.word_probs.get(t, 1e-8))
                    self.word_embeddings[t] += lr * d_p * w / len(p_tokens)

                # Renormalise updated embeddings
                for t in set(q_tokens + p_tokens):
                    vec = self.word_embeddings[t]
                    norm = np.linalg.norm(vec) + 1e-8
                    self.word_embeddings[t] = (vec / norm).astype(np.float32)

            if epoch % 5 == 0:
                logger.info(
                    "SIFEmbedder: contrastive epoch %d, avg loss=%.4f",
                    epoch,
                    total_loss / max(N, 1),
                )

        # Recompute first PC after fine-tuning
        if self.remove_pc:
            sentence_embs = []
            for q_tokens, p_tokens in zip(tokenized_queries, tokenized_positives):
                for tokens in (q_tokens, p_tokens):
                    emb = self._embed_sentence_raw(tokens)
                    if emb is not None:
                        sentence_embs.append(emb)
            if len(sentence_embs) >= 2:
                X = np.stack(sentence_embs)
                self._pc = self._power_iteration(X, max_iter=10)
                logger.info("SIFEmbedder: first PC recomputed after fine-tuning")

        logger.info("SIFEmbedder: contrastive fine-tuning complete")
        return self

    def get_state(self) -> dict:
        return {
            "latent_dim": self.latent_dim,
            "a": self.a,
            "remove_pc": self.remove_pc,
            "word_embeddings": {k: v.tolist() for k, v in self.word_embeddings.items()},
            "word_probs": self.word_probs,
            "pc": self._pc.tolist() if self._pc is not None else None,
        }

    def load_state(self, state: dict) -> "SIFEmbedder":
        self.latent_dim = state["latent_dim"]
        self.a = state["a"]
        self.remove_pc = state["remove_pc"]
        self.word_embeddings = {
            int(k): np.array(v, dtype=np.float32)
            for k, v in state["word_embeddings"].items()
        }
        self.word_probs = {int(k): v for k, v in state["word_probs"].items()}
        pc = state.get("pc")
        self._pc = np.array(pc, dtype=np.float32) if pc is not None else None
        return self
