"""SIF Sentence Embedder — Smooth Inverse Frequency for SOT v2.0.

Theoretical foundation:
    Arora et al. (2017) "A Simple but Tough-to-Beat Baseline for
    Sentence Embeddings" proves that under a generative model where
    sentences are generated by a random walk on a discourse vector,
    the optimal sentence embedding is:

        v_s = (1/|s|) Σ_{w∈s}  a / (a + p(w)) · v_w

    where p(w) is the unigram probability of word w, v_w is its word
    embedding, and a is a hyper-parameter (typically 1e-3 to 1e-4).

    After computing v_s, removing the first principal component from
    the corpus of sentence embeddings corrects for the common discourse
    direction and dramatically improves performance on semantic textual
    similarity tasks.

    This method is:
      - Unsupervised (no sentence-pair labels)
      - Theoretically grounded in a random-walk discourse model
      - Competitive with early SBERT variants on STS benchmarks
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)


class SIFEmbedder:
    """Smooth Inverse Frequency sentence embedder.

    Trains word embeddings via PMI-based matrix factorisation, then
    composes sentence embeddings via SIF weighting + PCA removal.
    """

    def __init__(
        self,
        latent_dim: int = 384,
        window_size: int = 5,
        min_count: int = 2,
        a: float = 1e-3,
        remove_pc: bool = True,
    ):
        self.latent_dim = latent_dim
        self.window_size = window_size
        self.min_count = min_count
        self.a = a
        self.remove_pc = remove_pc

        self.word_embeddings: Dict[int, np.ndarray] = {}
        self.word_probs: Dict[int, float] = {}
        self._pc: Optional[np.ndarray] = None  # First principal component

    # ------------------------------------------------------------------ #
    # Training
    # ------------------------------------------------------------------ #

    def fit(
        self,
        tokenized_docs: List[List[int]],
        vocab_size: int,
    ) -> "SIFEmbedder":
        """Fit word embeddings and sentence PCA on tokenized documents.

        Args:
            tokenized_docs: List of documents, each a list of token IDs.
            vocab_size: Total number of distinct token IDs.
        """
        logger.info(
            "SIFEmbedder: fitting on %d docs, vocab=%d, dim=%d",
            len(tokenized_docs),
            vocab_size,
            self.latent_dim,
        )

        # 1. Count unigrams and co-occurrences
        unigram_counts = np.zeros(vocab_size, dtype=np.float64)
        cooc_counts = np.zeros((vocab_size, vocab_size), dtype=np.float64)
        total_tokens = 0

        for doc in tokenized_docs:
            if not doc:
                continue
            for t in doc:
                if 0 <= t < vocab_size:
                    unigram_counts[t] += 1.0
                    total_tokens += 1
            w = self.window_size
            for i in range(len(doc)):
                for j in range(i + 1, min(i + w + 1, len(doc))):
                    a, b = doc[i], doc[j]
                    if 0 <= a < vocab_size and 0 <= b < vocab_size:
                        cooc_counts[a, b] += 1.0
                        cooc_counts[b, a] += 1.0

        if total_tokens == 0:
            raise ValueError("No tokens found in corpus")

        # Word probabilities
        self.word_probs = {
            t: float(unigram_counts[t]) / total_tokens
            for t in range(vocab_size)
            if unigram_counts[t] > 0
        }

        valid_mask = unigram_counts >= self.min_count
        n_valid = int(valid_mask.sum())
        logger.info(
            "SIFEmbedder: %d / %d tokens pass min_count=%d",
            n_valid,
            vocab_size,
            self.min_count,
        )

        if n_valid == 0:
            logger.warning("No valid tokens, using random embeddings")
            rng = np.random.default_rng(42)
            for t in range(vocab_size):
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb
            return self

        # 2. PMI matrix for valid tokens
        valid_idx = np.where(valid_mask)[0]
        idx_map = {int(v): i for i, v in enumerate(valid_idx)}
        u_counts = unigram_counts[valid_idx] + 1e-8
        c_counts = cooc_counts[np.ix_(valid_idx, valid_idx)]
        N = float(c_counts.sum()) + 1e-8

        log_cij = np.log(c_counts + 1e-8)
        log_ci = np.log(u_counts)
        log_cj = np.log(u_counts)
        import math
        pmi = log_cij + math.log(N) - log_ci[:, None] - log_cj[None, :]
        pmi = np.maximum(pmi, 0.0).astype(np.float32)

        # 3. Truncated SVD
        logger.info("SIFEmbedder: computing SVD on %dx%d PMI matrix...", n_valid, n_valid)
        U, S, Vt = np.linalg.svd(pmi, full_matrices=False)
        k = min(self.latent_dim, n_valid)
        Uk = U[:, :k]
        Sk = np.sqrt(S[:k])
        raw_emb = (Uk * Sk[None, :]).astype(np.float32)
        norms = np.linalg.norm(raw_emb, axis=1, keepdims=True) + 1e-8
        raw_emb /= norms

        for orig_t, sub_i in idx_map.items():
            emb = raw_emb[sub_i]
            if k < self.latent_dim:
                pad = np.zeros(self.latent_dim - k, dtype=np.float32)
                emb = np.concatenate([emb, pad])
            self.word_embeddings[orig_t] = emb

        rng = np.random.default_rng(42)
        for t in range(vocab_size):
            if t not in self.word_embeddings:
                emb = rng.standard_normal(self.latent_dim).astype(np.float32)
                emb /= np.linalg.norm(emb) + 1e-8
                self.word_embeddings[t] = emb

        # 4. Compute first principal component of sentence embeddings
        if self.remove_pc:
            sentence_embs = []
            for doc in tokenized_docs:
                emb = self._embed_sentence_raw(doc)
                if emb is not None:
                    sentence_embs.append(emb)
            if len(sentence_embs) >= 2:
                X = np.stack(sentence_embs)
                # First PC via power iteration (faster than full SVD)
                self._pc = self._power_iteration(X, max_iter=10)
                logger.info("SIFEmbedder: first principal component computed")

        logger.info("SIFEmbedder: fit complete")
        return self

    def _embed_sentence_raw(self, token_ids: List[int]) -> Optional[np.ndarray]:
        """SIF-weighted average without PC removal."""
        if not token_ids:
            return None
        vecs = []
        weights = []
        for t in token_ids:
            if t not in self.word_embeddings:
                continue
            p = self.word_probs.get(t, 1e-8)
            weight = self.a / (self.a + p)
            vecs.append(self.word_embeddings[t] * weight)
            weights.append(weight)
        if not vecs:
            return None
        emb = np.sum(vecs, axis=0) / (sum(weights) + 1e-8)
        return emb.astype(np.float32)

    def embed(self, token_ids: List[int]) -> np.ndarray:
        """Embed a sentence (list of token IDs) via SIF."""
        emb = self._embed_sentence_raw(token_ids)
        if emb is None:
            return np.zeros(self.latent_dim, dtype=np.float32)
        if self._pc is not None and self.remove_pc:
            # Remove projection onto first PC
            emb = emb - emb.dot(self._pc) * self._pc
        norm = np.linalg.norm(emb) + 1e-8
        return (emb / norm).astype(np.float32)

    @staticmethod
    def _power_iteration(X: np.ndarray, max_iter: int = 10) -> np.ndarray:
        """Compute dominant eigenvector of X^T X via power iteration."""
        v = np.random.default_rng(42).standard_normal(X.shape[1]).astype(np.float32)
        v /= np.linalg.norm(v) + 1e-8
        for _ in range(max_iter):
            v = X.T @ (X @ v)
            v /= np.linalg.norm(v) + 1e-8
        return v.astype(np.float32)

    def get_state(self) -> dict:
        return {
            "latent_dim": self.latent_dim,
            "a": self.a,
            "remove_pc": self.remove_pc,
            "word_embeddings": {k: v.tolist() for k, v in self.word_embeddings.items()},
            "word_probs": self.word_probs,
            "pc": self._pc.tolist() if self._pc is not None else None,
        }

    def load_state(self, state: dict) -> "SIFEmbedder":
        self.latent_dim = state["latent_dim"]
        self.a = state["a"]
        self.remove_pc = state["remove_pc"]
        self.word_embeddings = {
            int(k): np.array(v, dtype=np.float32)
            for k, v in state["word_embeddings"].items()
        }
        self.word_probs = {int(k): v for k, v in state["word_probs"].items()}
        pc = state.get("pc")
        self._pc = np.array(pc, dtype=np.float32) if pc is not None else None
        return self
