# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from rtmdk.server.proto import rtmdk_pb2 as rtmdk_dot_server_dot_proto_dot_rtmdk__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in rtmdk/server/proto/rtmdk_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RTMDKStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/rtmdk.RTMDK/Health",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.QueryMemory = channel.unary_unary(
            "/rtmdk.RTMDK/QueryMemory",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryResponse.FromString,
            _registered_method=True,
        )
        self.CreateNode = channel.unary_unary(
            "/rtmdk.RTMDK/CreateNode",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeResponse.FromString,
            _registered_method=True,
        )
        self.GetNode = channel.unary_unary(
            "/rtmdk.RTMDK/GetNode",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.GetNodeRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.Node.FromString,
            _registered_method=True,
        )
        self.DeleteNode = channel.unary_unary(
            "/rtmdk.RTMDK/DeleteNode",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeResponse.FromString,
            _registered_method=True,
        )
        self.BatchIngest = channel.unary_unary(
            "/rtmdk.RTMDK/BatchIngest",
            request_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestRequest.SerializeToString,
            response_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestResponse.FromString,
            _registered_method=True,
        )


class RTMDKServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QueryMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchIngest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RTMDKServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthResponse.SerializeToString,
        ),
        "QueryMemory": grpc.unary_unary_rpc_method_handler(
            servicer.QueryMemory,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryResponse.SerializeToString,
        ),
        "CreateNode": grpc.unary_unary_rpc_method_handler(
            servicer.CreateNode,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeResponse.SerializeToString,
        ),
        "GetNode": grpc.unary_unary_rpc_method_handler(
            servicer.GetNode,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.GetNodeRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.Node.SerializeToString,
        ),
        "DeleteNode": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteNode,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeResponse.SerializeToString,
        ),
        "BatchIngest": grpc.unary_unary_rpc_method_handler(
            servicer.BatchIngest,
            request_deserializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestRequest.FromString,
            response_serializer=rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("rtmdk.RTMDK", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rtmdk.RTMDK", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RTMDK(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/Health",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QueryMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/QueryMemory",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.QueryMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/CreateNode",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.CreateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/GetNode",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.GetNodeRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.Node.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/DeleteNode",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchIngest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rtmdk.RTMDK/BatchIngest",
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestRequest.SerializeToString,
            rtmdk_dot_server_dot_proto_dot_rtmdk__pb2.BatchIngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
