global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rtmdk'
    static_configs:
      - targets: ['rtmdk:8080']
    metrics_path: /metrics

rule_files:
  - 'alerts.yml'
